version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout

      # Buat file local.properties dengan API_TOKEN
      - run:
          name: Create local.properties
          command: |
            echo "sdk.dir=$ANDROID_HOME" > local.properties
            echo "API_TOKEN=$API_TOKEN" >> local.properties

      # Berikan izin eksekusi pada gradlew
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew

      # Restore cache
      - restore_cache:
          keys:
            - android-orb-v1-

      # Install dependencies
      - run:
          name: Install Dependencies
          command: ./gradlew androidDependencies

      # Save cache
      - save_cache:
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
          key: 'android-orb-v1-{{ epoch }}'

      # Run Ktlint Check
      - run:
          name: Check Code Style
          command: ./gradlew checkCodeStyle

      # Run unit tests
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebug

      # Generate Jacoco Report
      - run:
          name: Generate Jacoco Report
          command: ./gradlew jacocoTestReport

      # Build debug APK
      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug

      # Store APK as artifact
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apk

      # Store Jacoco Report as artifact
      - store_artifacts:
          path: app/build/reports/jacoco
          destination: jacoco-report

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test